#!/usr/bin/env node

const program = require('commander');

const {initializeGradebook, addStudent, importRoster, showGradebook, addGradeColumn, addGrade} = require('./index');

program
  .version('1.0.0')
  .description('Gradebook API')

program
  .command('init')
  .description('Create a new empty grade book')
  .action(() => initializeGradebook());

program
  .command('addstudent')
  .alias('as')
  .description('Add student')
  .action(() => addStudent());

program
  .command('import <file> <course> <section>')
  .description('Import Banner roster')
  .action((file, course, section) => importRoster(file, course, section));

program
  .command('show')
  .description('Show full gradebook')
  .action(() => showGradebook());

program
  .command('addgradecolumn <colname>')
  .alias('agc')
  .description('Add a new grade column')
  .action((colname) => addGradeColumn(colname));

program
  .command('addgrade <colname> <student> <score>')
  .alias('ag')
  .description('Add student score')
  .action((colname, student, score) => addGrade(colname, student, score));


program.parse(process.argv);
