#!/usr/bin/env node

const program = require('commander');

const {initializeGradebook, addStudent, importRoster, showGradebook, addGradeColumn, addGrade, takeAttendance} = require('./index');

program
  .version('1.0.0')
  .description('Gradebook API')

program
  .command('init <course> <section>')
  .description('Create a new empty grade book')
  .action((course, section) => initializeGradebook(course, section));

program
  .command('addstudent')
  .alias('as')
  .description('Add student')
  .action(() => addStudent());

program
  .command('import <file> <course> <section>')
  .description('Import Banner roster')
  .action((file, course, section) => importRoster(file, course, section));

program
  .command('addgradecolumn <colname> <course> <section>')
  .alias('agc')
  .description('Add a new grade column')
  .action((colname, course, section) => addGradeColumn(colname, course, section));

program
  .command('addgrade <colname> <student> <score>')
  .alias('ag')
  .description('Add student score')
  .action((colname, student, score) => addGrade(colname, student, score));

program
  .command('show')
  .description('Show gradebook')
  .option('-s, --student <name>', 'Show only one student')
  //.action((options.student) => showGradebook(options.student));
  .action( function(options) { showGradebook(options.student) } );

program
  .command('attendance <course> <section>')
  .alias('att')
  .description('Take attendance for a class')
  .action((course, section) => takeAttendance(course, section));


program.parse(process.argv);
